Does not link with the following error on an example
```
    > run -verbose
    [info] Linking (758 ms)
    [info] Discovered 1270 classes and 9347 methods
    [info] Optimizing (734 ms)
    [info] Generating intermediate code (225 ms)
    [info] Produced 37 files
    [info] Compiling to native code (672 ms)
    [error] Undefined symbols for architecture x86_64:
    [error]   "_scalanative_c_iwgrp", referenced from:
    [error]       _Main$::main_scala.scalanative.runtime.ObjectArray_unit in __empty.ll.o
    [error] ld: symbol(s) not found for architecture x86_64
    [error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
    [info] Linking native code (86 ms)
    java.io.IOException: Cannot run program "/Users/adam/scala/scala-native-examples/cpio-example/target/scala-2.11/cpio-example-out": error=2, No such file or directory
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    Caused by: java.io.IOException: error=2, No such file or directory
            at java.lang.UNIXProcess.forkAndExec(Native Method)
            at java.lang.UNIXProcess.<init>(UNIXProcess.java:185)
            at java.lang.ProcessImpl.start(ProcessImpl.java:134)
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    [trace] Stack trace suppressed: run last compile:run for the full output.
    [error] (compile:run) java.io.IOException: Cannot run program "/Users/adam/scala/scala-native-examples/cpio-example/target/scala-2.11/cpio-example-out": error=2, No such file or directory
    [error] Total time: 3 s, completed Nov 25, 2017 11:44:27 PM
```